FROM kalilinux/kali-rolling:latest

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    nmap \
    hydra \
    metasploit-framework \
    hping3 \
    curl \
    iputils-ping \
    net-tools \
    && rm -rf /var/lib/apt/lists/*

CMD ["tail", "-f", "/dev/null"]
