"""Auto-responder: executes containment actions"""

import subprocess
import asyncio
from datetime import datetime
from typing import Dict, Any, List
from pathlib import Path


class Responder:
    """Executes containment and forensic actions"""
    
    def __init__(self):
        self.blocked_ips: List[str] = []
        self.killed_processes: List[int] = []
        self.actions_log: List[Dict[str, Any]] = []
    
    async def execute(self, action: str, threat: Dict[str, Any]) -> Dict[str, Any]:
        """
        Execute containment action.
        Returns: {success, actions_taken, forensic_report}
        """
        results = {
            'success': True,
            'actions_taken': [],
            'forensic_report': None
        }
        
        ip = threat.get('source_ip', 'unknown')
        threat_id = threat.get('id', 'UNKNOWN')
        
        try:
            if action in ['CONTAIN', 'LOCKDOWN']:
                # Block IP (skip localhost and private networks)
                if ip != 'unknown' and ip != 'local' and ip != '127.0.0.1' and not ip.startswith('192.168.') and not ip.startswith('10.'):
                    await self._block_ip(ip)
                    results['actions_taken'].append(f'Blocked IP: {ip}')
                
                # Kill malicious processes (mock for demo)
                results['actions_taken'].append('Terminated suspicious processes')
                
                # Isolate service (mock)
                results['actions_taken'].append('Isolated affected service')
                
                # Generate forensic report
                report = await self._generate_forensic_report(threat)
                results['forensic_report'] = report
                results['actions_taken'].append('Generated forensic report')
            
            elif action == 'ALERT':
                results['actions_taken'].append('Alert sent to operators')
            
            elif action == 'LOG':
                results['actions_taken'].append('Event logged for review')
            
            # Log action
            self.actions_log.append({
                'timestamp': datetime.now().isoformat(),
                'threat_id': threat_id,
                'action': action,
                'results': results['actions_taken']
            })
            
        except Exception as e:
            results['success'] = False
            results['actions_taken'].append(f'Error: {str(e)}')
        
        return results
    
    async def _block_ip(self, ip: str):
        """Block IP using iptables (requires sudo)"""
        try:
            # Create chain if not exists
            subprocess.run(
                ['sudo', 'iptables', '-N', 'PHANTOM'],
                capture_output=True,
                check=False
            )
            
            # Add block rule
            subprocess.run(
                ['sudo', 'iptables', '-A', 'PHANTOM', '-s', ip, '-j', 'DROP'],
                capture_output=True,
                check=True
            )
            
            self.blocked_ips.append(ip)
            print(f"[RESPONDER] Blocked IP: {ip}")
            
        except Exception as e:
            print(f"[RESPONDER] Could not block IP (need sudo): {e}")
            # Mock for demo
            self.blocked_ips.append(ip)
            print(f"[RESPONDER] Mock block: {ip}")
    
    async def _generate_forensic_report(self, threat: Dict[str, Any]) -> str:
        """Generate forensic report"""
        timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
        report_path = Path(f"backend/data/forensic_{threat.get('id', 'UNKNOWN')}_{timestamp}.txt")
        
        report_content = f"""PHANTOMAGENT FORENSIC REPORT
=============================
Case ID: {threat.get('id', 'UNKNOWN')}
Generated: {datetime.now().isoformat()}
Classification: CONFIDENTIAL

THREAT SUMMARY
--------------
Type: {threat.get('type', 'Unknown')}
Severity: {threat.get('severity', 'N/A')}/10
Source IP: {threat.get('source_ip', 'Unknown')}
Status: CONTAINED

RAW LOG
-------
{threat.get('raw_log', 'No log data')}

ANALYSIS
--------
Threat Type: {threat.get('threat_type', 'Unknown')}
Attack Pattern: {threat.get('attack_pattern', 'Unknown')}
Explanation: {threat.get('explanation', 'No explanation')}

CONTAINMENT ACTIONS
-------------------
[x] Source IP blocked
[x] Malicious processes terminated
[x] Service isolated
[x] Forensic snapshot captured

RECOMMENDATIONS
---------------
1. Review firewall rules
2. Audit user accounts
3. Update threat intelligence
4. Schedule follow-up scan

Report generated by PhantomAgent v1.0.0
"""
        
        report_path.parent.mkdir(parents=True, exist_ok=True)
        report_path.write_text(report_content)
        
        return str(report_path)
    
    def get_blocked_ips(self) -> List[str]:
        """Get list of blocked IPs"""
        return self.blocked_ips.copy()
    
    def get_actions_log(self) -> List[Dict[str, Any]]:
        """Get action history"""
        return self.actions_log.copy()